version: "2"

services:
  redis:
    image: tutum/redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data
    environment:
      REDIS_PASS: "**None**"

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret

  zookeeper:
    image: jplock/zookeeper:3.4.6
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: ches/kafka
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - kafka-data:/data
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.103
      ZOOKEEPER_IP: zookeeper
    
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: app
    volumes:
      - ".:/deploy"
    command: bash -c 'while true; do sleep 10; done'

volumes:
  redis-data:
  rabbit-data:
  kafka-data:
