version: "2"

services:
  cq3-redis:
    image: tutum/redis
    container_name: cq3-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_PASS: "**None**"

  cq3-rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile.rabbitmq
    container_name: cq3-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret

  cq3-sqs:
    container_name: cq3-sqs
    image: softwaremill/elasticmq-native
    ports:
      - "9324:9324"

