FROM rabbitmq:management
RUN apt-get update && apt-get install -y python wget
RUN wget https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_6/bin/rabbitmqadmin
RUN chmod +x rabbitmqadmin
